language: r
sudo: required
warnings_are_errors: true
cache: packages
dist: xenial

r:
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libgsl-dev
    - libgdal-dev
    - libproj-dev
