#' A visualization tool of diagnostics of fitted model in the partial association analysis
#'
#' A plot matrix to display the QQ-plot of each fitted model when conducting the partial
#' association analyses. Based on the input of "PAsso" object, each plot stands for the
#' QQ-plot of the surrogate residuals of fitted models. All the plots are based on the
#' surrogate residuals generated from \code{"resides"} function.Graphics are designed
#' based on \code{\link{ggplot2}}.
#'
#' @param object The object in "PAsso" class that is generated by "test" or "PAsso".
#' @param output A character string specifying what output to plot. Default is \code{"qq"} which
#' produces a quantile-quantile plots of the residuals. \code{"fitted"} will give a matrix
#' plot between residuals and fitted response. \code{"covariates"} will give a matrix plot
#' between each residual and each covariate.
#' @param ... Additional optional arguments for drawing plots to be passed onto.
#'
#' @return A list contains plots of \code{"ggplot"} object
#'
#' @rdname check.model
#'
#'
#' @export
#'
#' @examples
#' # import data -------------------------------------------------------------
#' data("nes2016_pre")
#' # "PAsso" function: input three responses ----------------------------
#' PAsso_2 <- PAsso(responses = c("Prevote.num", "PID", "selfLR"),
#'                 adjustments = c("income.num", "age", "edu.year"),
#'                 data = nes2016)
#' summary(PAsso_2, digits=4)
#'
#' check_qq <- check.model(object = PAsso_2, color="blue",output = "qq")
#'
#' check_fitted <- check.model(object = PAsso_2, output = "fitted")
#'
#' check_covar <- check.model(object = PAsso_2, output = "covariate")
#'
check.model <- function(
  object,
  output = c("qq", "fitted", "covariate"),
  ...
) {
  # object = PAsso_2; output = "covariate"

  # What type of output plot to produce
  output <- match.arg(output, several.ok = FALSE)
  rep_SRs <- object$rep_SRs
  resp_name <- attr(object, "responses")

  n_resp <- length(resp_name)
  nCol <- floor(sqrt(n_resp))
  plot_list <- list()

  # return a matrix-plot including diagnostics of models.
  if (output == "qq") {
    for (i in 1:n_resp) {
      plot_list[[i]] <-
        # autoplot(rep_SRs[,1,i], what = output,
        autoplot(object$fitted.models[[i]], what = output,
                 distribution = qnorm, resp_name = resp_name[i], ...)
    }

    do.call("grid.arrange", c(plot_list, ncol=nCol))

    # test_SRs <- data.frame(SRs=rep_SRs[,1,], Resp=rep(resp_name, each=1690))
    #
    # test0 <- autoplot.resid(test_SRs[,1], what = output,
    #                # distribution = qnorm, title = resp_name[i], ...)
    #                distribution = qnorm)
    #
    # test0 <- ggplot(test_SRs, aes(x=test_SRs$SRs))
    #
    # test0 + facet_wrap(~ Resp, ncol=3)
    #

  } else if (output == "fitted") {

    for (i in 1:n_resp) {
      plot_list[[i]] <-
        autoplot(object$fitted.models[[i]], what = output, resp_name = resp_name[i],
                 alpha = 0.5, ...)
    }
    do.call("grid.arrange", c(plot_list, ncol=nCol))

  } else {
    adjust_name <- attr(object, "adjustments")
    n_adjust <- length(adjust_name)
    t_lenght <- n_resp*n_adjust
    adjust_id <- rep(1:n_adjust, times=n_resp) # make index for covariate name in the for loop
    resp_id <- rep(1:n_resp, each=n_adjust) # make index for response name in the for loop

    for (i in 1:(t_lenght)) {
      plot_list[[i]] <-
        autoplot(object$fitted.models[[resp_id[i]]], what = "covariate",
                 x = object$data[,adjust_name[adjust_id[i]]],
                 xlab = adjust_name[adjust_id[i]],
                 # resp_name = resp_name[resp_id[i]], ...)
                 resp_name = resp_name[resp_id[i]])

      if (i %% n_adjust != 1) { # First plot of each response, draw ylab, otherwise, no ylab
        plot_list[[i]] <- plot_list[[i]] + ylab("")
      }
      if ((i-1) %/% n_adjust != (n_resp-1)) { # last row of plot(last response), draw xlab, otherwise, no xlab
        plot_list[[i]] <- plot_list[[i]] + xlab("")
      }
    }
    do.call("grid.arrange", c(plot_list, ncol=n_adjust))
  }

  return(plot_list)
}

