#' @title A matrix of partial regression plots between responses after adjustments
#'
#' @description A plot matrix to display the results of partial association analyses. Upper-triangle contains
#' scatter-plot matrix between each pair of response variables. Lower-triangle contains the
#' partial correlation coefficients adjusted by covariates.
#'
#' @details A pairwise plot matrix reveals the partial association between ordinal variables.
#' All the plots are based on surrogate residuals generated from \code{"resides"} function.
#' Graphics are designed based on \code{\link{ggplot2}} and \code{"GGally"}.
#'
#' @param x the object in "PAsso" class that is generated by "PAsso" or "test".
#' @param ... Additional optional arguments to be passed onto.
#'
#' @return A \code{"GGally"} object.
#' @import GGally
#'
#'
#' @export
#'
#' @examples
#' data(nes2016_pre)
#'
#' summary(nes2016_pre)
#'
#' PAsso_1 <- PAsso(responses = c("Prevote.num", "PID"),
#'                  adjustments = c("income.num", "age", "edu.year"),
#'                  data = nes2016_pre)
#'
#' plot(x = PAsso_1)
#'
plot <- function(x, y, ...) {
  UseMethod("plot")
}


#' @param x A PAsso object for drawing partial regression plot.
#' @param color The color of points.
#' @param ...
#'
#' @rdname plot
#' @method plot PAsso
#' @export
plot.PAsso <- function(
  x, color="blue", ...
) {
  # x <- PAsso_1; color="blue"

  resid_Mat <- as.data.frame(x$rep_SRs[,1,])
  cor_method <- attr(x, "arguments")[2]

  GGally::ggpairs(resid_Mat,
         upper = list(
           continuous = GGally::wrap("smooth_loess", colour=color, ...)),
         # diag = list(continuous = wrap("barDiag", colour = color)),
         # lower = list(continuous = GGally::wrap("cor", method="kendall")),
         lower = list(continuous = GGally::wrap("cor", method = cor_method, ...)),
         # lower = list(continuous = x$corr[upper.tri(x$corr)]),
         ...
 )
}

