#' A visualization tool of the partial association analyses (plot matrix)
#'
#' A plot matrix to display the results of partial association analyses. Upper-triangle contains
#' scatter-plot matrix between each pair of response variables. Lower-triangle contains the
#' partial correlation coefficients adjusted by covariates.
#'
#' A pairwise plot matrix reveals the partial association between ordinal variables.
#' All the plots are based on surrogate residuals generated from \code{"resides"} function.
#' Graphics are designed based on \code{\link{ggplot2}} and \code{"GGally"}.
#'
#' @param object the object in "PAsso" class that is generated by "corr.test" or "corr".
#' @param color spedify the points color.
#' @param ... Additional optional arguments to be passed onto.
#'
#' @return A \code{"GGally"} object.
#' @import GGally
#'
#' @rdname plot
#' @method plot PAsso
#'
#'
#' @export
#'
#' @examples
#' data(nes2016)
#'
#' summary(nes2016)
#'
#' PAsso_1 <- PAsso(responses = c("Prevote.num", "PID"), adjustments = c("income.num", "age", "edu.year"), data = nes2016)
#'
#' plot(object = PAsso_1, colour="blue")
#'
plot.PAsso <- function(
  object,
  color="blue", ...
) {
  # object <- PAsso_1; color="blue"

  resid_Mat <- as.data.frame(object$rep_SRs[,1,])
  cor_method <- attr(object, "arguments")[2]

  GGally::ggpairs(resid_Mat,
         upper = list(
           continuous = GGally::wrap("smooth_loess", colour=color)),
         # diag = list(continuous = wrap("barDiag", colour = color)),
         # lower = list(continuous = GGally::wrap("cor", method="kendall")),
         lower = list(continuous = GGally::wrap("cor", method =cor_method)),
         # lower = list(continuous = object$corr[upper.tri(object$corr)]),
         ...
 )
}

